# Generated by Django 3.1.6 on 2026-03-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_add_hearted_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='max_price_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max $ per seat (leave blank for free/carpool)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='origination_state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='person',
            name='service_tier',
            field=models.CharField(choices=[('regular', 'Regular CartyCity'), ('premium', 'Premium CartyCity')], default='regular', max_length=16),
        ),
        migrations.AddField(
            model_name='person',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('hatchback', 'Hatchback')], default='', max_length=32),
        ),
    ]
